# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12K06_30rpTBfx8Jkk7B4kF_PDheLv12W
"""

# Juego ahorcado
import random


print('\033[1m', '''
Bienvenido al ahorcado.
Empieza introduciendo la letra deseada.
Una vez sepas la palabra introduce "*", a continuación aparecerá otro recuadro en el cual podrás introducir la palabra.
''', '\033[0m')
imagenes = ['''

  +---+
  |   |
  O   |
      |
      |
      |
=========''', '''

  +---+
  |   |
  O   |
  |   |
      |
      |
=========''', '''

  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''

  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========''', '''

  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========''', '''

  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========''']
palabras = ["CELDA", "SUECIA", "PAISAJE", "CONSULTA", "BURBUJA", "INTERCEPTAR", "JUEGOS", "DESPERTADOR", "ACERTIJO"]
palabra_selec = random.choices(palabras, k=1)    # Seleccionar palabra random de la lista
#print(palabra_selec)           # Ver que palabra se ha seleccionado
palabra_selec = "".join(map(str, palabra_selec))   # Transformar list a str
longitud_palabra = len(palabra_selec)      # Calcular la longitud de la palabra
print("Numero de letras: ",longitud_palabra)
i = 0
numero_huecos = 0
letras_error = 0
lista_error = []

avance = ""
while numero_huecos < longitud_palabra:
  avance = avance + "_ "
  numero_huecos += 1

print (avance)
while i < longitud_palabra:
  posicion = 0
  letra = input("Introducir letra: ")
  letra = letra.upper()
  if letra.isalpha():
    if letra in palabra_selec:
      for x in palabra_selec:
        if x == letra:
          #print("entra")
          lst = list(avance)
          lst[posicion] = x
          avance = ''.join(lst) 
        posicion += 2
      print(avance)

    else:
      if letra not in lista_error:
        print(imagenes[letras_error])
        letras_error += 1
        lista_error.append(letra)
      print("\033[1;31m","Letras que no aparecen: ",lista_error,'\033[0m')
      print(avance)
      if letras_error == 6:
        print("\033[31m","\U0001F641 Has superado las oportunidades. La palabra era: ",palabra_selec,"\033[0m")
        i = 30

  if letra == "*":
    palabra_introd = input("Introducir la palabra: ")
    palabra_introd = palabra_introd.upper()
    if palabra_introd == palabra_selec:
      print('\033[36m',"\U0001F603 Has adivinado la palabra \U0001F603",'\033[0m')
      i = 30
    else:
      print("Sigue intentandolo")